// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPyfVfeNzCJCVtPNEF36BJA2RItG-YMso',
    appId: '1:138643934150:web:39956da32d53d1cdae40c7',
    messagingSenderId: '138643934150',
    projectId: 'recipe-app-f0609',
    authDomain: 'recipe-app-f0609.firebaseapp.com',
    storageBucket: 'recipe-app-f0609.appspot.com',
    measurementId: 'G-BQSLG8GPLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOWWhy-GQQAD_JWjFebkN80MLmqC-uzno',
    appId: '1:138643934150:android:ba752d044d5fa4f5ae40c7',
    messagingSenderId: '138643934150',
    projectId: 'recipe-app-f0609',
    storageBucket: 'recipe-app-f0609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfeB-PKOn2vB0Z3lkOR8BGWGIyBO-wV3Q',
    appId: '1:138643934150:ios:74fc09c33680e388ae40c7',
    messagingSenderId: '138643934150',
    projectId: 'recipe-app-f0609',
    storageBucket: 'recipe-app-f0609.appspot.com',
    iosClientId: '138643934150-pcr6nnr7csnffg3qp2ocro6va0bg0j0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfeB-PKOn2vB0Z3lkOR8BGWGIyBO-wV3Q',
    appId: '1:138643934150:ios:74fc09c33680e388ae40c7',
    messagingSenderId: '138643934150',
    projectId: 'recipe-app-f0609',
    storageBucket: 'recipe-app-f0609.appspot.com',
    iosClientId: '138643934150-pcr6nnr7csnffg3qp2ocro6va0bg0j0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
